- src/main/target/STRIXF10/target.h
From 22/07/2018 until the release of Betaflight 3.5.0 (scheduled for 05/08/2018), the project is in a 'feature freeze / release candidate' phase. This means:
1. Pull requests can still be submitted as normal. Comments / discussions will probably be slower than normal due to shifted priorities;
2. If your pull request is a fix for an existing bug, or an update for a single target that has a low risk of side effect for other targets, it will be reviewed, and if accepted merged into `master` for the 3.5 release;
3. All other pull requests will be scheduled for 4.0, and discussed / reviewed / merged into `master` after 3.5.0 has been released. Please keep in mind that this potentially means that you will have to rebase your changes if they are broken by bugfixes made for 3.5.
1. Pull requests …
> Fix for the STRIXF10 - made the buzzer works

- src/main/interface/msp.c
- src/main/interface/msp_protocol.h
From 22/07/2018 until the release of Betaflight 3.5.0 (scheduled for 05/08/2018), the project is in a 'feature freeze / release candidate' phase. This means:
1. Pull requests can still be submitted as normal. Comments / discussions will probably be slower than normal due to shifted priorities;
2. If your pull request is a fix for an existing bug, or an update for a single target that has a low risk of side effect for other targets, it will be reviewed, and if accepted merged into `master` for the 3.5 release;
3. All other pull requests will be scheduled for 4.0, and discussed / reviewed / merged into `master` after 3.5.0 has been released. Please keep in mind that this potentially means that you will have to rebase your changes if they are broken by bugfixes made for 3.5.
1. Pull requests …
> adding gps_recue in msp protocol and interface

- Makefile
- src/main/flight/pid.c
> make heliospring the default fc

- src/main/target/AIRBOTF7/target.c
- src/main/target/AIRBOTF7/target.h
- src/main/target/AIRBOTF7/target.mk
- src/main/target/AIRF7/config.c
- src/main/target/AIRF7/target.c
- src/main/target/AIRF7/target.h
- src/main/target/AIRF7/target.mk
adding the AIRBOTF7 and AIRF7 targets.
> add new racerstar and airbot targets (F7 variant)

- .travis.yml
- make/tools.mk
- src/main/build/version.h
- src/main/cms/cms_menu_imu.c
- src/main/common/filter.h
- src/main/common/kalman.c
- src/main/flight/pid.c
- src/main/flight/pid.h
- src/main/flight/position.c
- src/main/interface/msp.c
- src/main/interface/msp_protocol.h
- src/main/interface/settings.c
- src/main/msc/emfat_file.c
- src/main/sensors/gyro.c
- src/main/sensors/gyro.h
- src/main/sensors/gyro_filter_impl.h
- src/main/sensors/voltage.c
- src/main/target/HELIOSPRING/target.h
- src/main/target/MODE2FLUX/target.h
- src/main/target/STRIXF10/target.h
Putting Feathered pids as a slider instead of an on or off feature. Also breaking up the imuf q values on non helio fc to be set per axis. Lastly adding the dynamic biquad filter the in the helio imuf. More work to be done on that.
> Feathered slider

- src/main/fc/fc_core.c
https://github.com/emuflight/EmuFlight/issues/42#issuecomment-553383377
> possible fix for #42 (telemetry jitter)

- src/main/drivers/max7456.c
https://github.com/betaflight/betaflight/commit/78befad3b8b5eefa3cab65cce5ec7402388a8614
> possible fix for #34 (osd glitching)

- src/main/interface/msp_protocol.h
increment msp api to 1.44 for v0.2.12+
> increment msp api for v0.2.12+ [skip ci]

- .github/issue_template.md
- .github/pull_request_template.md
- README.md
shows travis build status for master, not Main
updated pull request template (age of emu)
> master of none (and Main)

- .github/FUNDING.yml
> create funding meta

- src/main/cms/cms_menu_imu.c
- src/main/flight/pid.c
- src/main/flight/pid.h
- src/main/interface/settings.c
Remove current implementation of cinematic setpoint to make room for new versions :) Current version is buggy anyhow
The first step in getting a correct implementation of this to work.
> remove cinematic setpoint

- src/main/interface/msp.c
1. Pull requests will only be accepted if they are opened against the `master` branch. Pull requests opened against other branches without prior consent from the maintainers will be closed;
2. Please follow the coding style guidlines: https://github.com/emuflight/EmuFlight/blob/master/docs/development/CodingStyle.md
3. Keep your pull requests as small and concise as possible. One pull request should only ever add / update one feature. If the change that you are proposing has a wider scope, consider splitting it over multiple pull requests. In particular, pull requests that combine changes to features and one or more new targets are not acceptable.
4. Ideally, a pull request should contain only one commit, with a descriptive message. If your changes …
> fix msp for helio imuf setting by gui

- .github/workflows/build.yml
works in parallel to travis and is worth exploring. adds a additional status check, too.
> add workflow for github actions to build

- src/main/flight/pid.c
Part of the horizon mode code is not currently being used. So I removed the excess code.
> remove unused code

- src/main/common/kalman.c
Reverts emuflight/EmuFlight#129
Just now had a chance to try this and it does not work at all. I thought it would fix it but it does not :( the kalman is more broken now. needs to be reverted asap
> Revert "Fix a bug in kalman.c?"

- src/main/fc/rc_controls.c
Zoe FPV had a suggestion for 3D and I figure she knows 3D better than me so here we are. Making the default 3D deadband smaller around center throttle.
> Update Defaults for 3D

- src/main/target/AIKONF7/target.h
> Kaio fixed AIKONF7 BB.

- src/main/target/HGLRCF411/target.c
- src/main/target/HGLRCF411/target.h
- src/main/target/HGLRCF411/target.mk
Kaio reported tested and working.
> Kaio created HGLRCF411 target

- src/main/common/kalman.c
Some issues with this kalman filter were brought to my attention. I have since been playing with it and getting it fixed. So far this works for me. I'll be having more people test it and see what they think as well, but it should make this filter more similar to the filter in the helio fc which should be for the better me thinks. Pushing this again as the last one had stick pids in it as well, which I did not want.
> Fix kalman.c

- .travis.sh
Based on https://unix.stackexchange.com/questions/45583/argument-list-too-long-how-do-i-deal-with-it-without-changing-my-command
> Potential travis fix

- src/main/drivers/max7456_symbols.h
Kaio found issue & best solution
> fix double throttle in OSD

- src/main/flight/pid.c
after adding a debug mode to smart smoothing I found that it did not work as expected. So I've gone and updated it. It now works a lot better. Added a change to the defaults as well now because of this. This is why logging can be so important :)
> Smart smoothing fix

- src/main/cms/cms_menu_imu.c
> trottle to throttle

- src/main/sensors/battery.c
much better default for the ibat lpf filter.
> Change ibat lpf period to 10

- .travis.sh
- src/main/build/version.h
- src/main/cms/cms_menu_imu.c
- src/main/fc/controlrate_profile.c
- src/main/fc/controlrate_profile.h
- src/main/flight/mixer.c
- src/main/flight/pid.c
- src/main/flight/pid.h
- src/main/interface/msp.c
- src/main/interface/settings.c
- src/main/sensors/battery.c
- src/main/sensors/battery.h
* reverts https://github.com/emuflight/EmuFlight/pull/153 - not ready for flight
* bumps version
* hotfixes travis
> revert #153

- src/main/target/GRAVITYF7/config.c
- src/main/target/GRAVITYF7/target.c
- src/main/target/GRAVITYF7/target.h
- src/main/target/GRAVITYF7/target.mk
Add please target: GRAVITYF7
Manufacturer: FLMD
link: www.flymod.net
> add target GRAVITYF7

- src/main/target/IFF7_TWIN_G/target.h
- src/main/target/VIVAF4AIO/target.c
- src/main/target/VIVAF4AIO/target.h
- src/main/target/VIVAF4AIO/target.mk
> Iflight f7

- src/main/interface/msp.c
- src/main/interface/msp_protocol.h
* MSP by loutwice
* requires Configurator 0.2.24
* prefer build next PR for firmware version bump 0.2.50
> fixed MSP 1.46 updating for angle_expo & horizon features

- README.md
Under the `Configuration Tool` in the Readme there's still some mentions of Betaflight. I guess this is a bug and not a feature. :)
> Small readme typo fix

- .github/workflows/build.yml
- src/main/build/version.h
kinda sorta self explanatory :)
> github actions compile fix

- .github/workflows/build.yml
- Makefile
- src/main/build/version.h
adopt Makefile so it should work for both travis and github actions; enhanced semantics for the github actions build; fixed artifacts not getting stored on pull requests; minor formatting of Makefile
> github compile fix aftermath

- .github/workflows/build.yml
- src/main/build/version.h
https://github.com/emuflight/EmuFlight/actions/runs/83409185
> fix artifacts filename not containing build number

- src/main/target/BETAFPVF411_V3/target.c
- src/main/target/BETAFPVF411_V3/target.h
- src/main/target/BETAFPVF411_V3/target.mk
add target betafpvf411 v3
similar to matekf411 but with BB enabled
> BETAFPVF411_V3

- src/main/build/version.h
* SDS fix #197
* Nbdinfinity fix #198
> bump version 0.2.52

- src/main/build/version.h
This reverts commit 4cfd027698e6d8eceb2a906d3fa042ad6a89790a.
> Revert "Update version.h (#207)"

- Makefile
* add commit SHA
* add Travis build number if applicable
> informative .hex names

- .github/workflows/build.yml
testing parallel builds (matrix)
> github workflow matrix (3 parallel builds are faster than 1)

- src/main/cms/cms_menu_imu.c
- src/main/interface/msp.c
- src/main/interface/msp_protocol.h
- src/main/sensors/gyroanalyse.c
dynNotchMinHz used to look like it was configurable, however, it was not. So I have fixed it so that it now is properly configurable.
> Fix dynNotchMinHz

- src/main/config/feature.h
Make the defaults now correct and make everything happy :)
> Fix gui issues

- src/main/build/version.h
- src/main/config/feature.h
updating numbering to help with release
> increment version number to 0.3.1

- src/main/build/version.h
- src/main/config/feature.h
- src/main/interface/msp.c
Fixed Battery average cell voltage for the DJI OSD
> Added additional battery voltage field to OSD

- src/main/build/version.h
- src/main/config/feature.h
- src/main/flight/pid.c
- src/main/telemetry/crsf.c
- src/test/unit/telemetry_crsf_unittest.cc
as seen in https://github.com/betaflight/betaflight/commit/0d7f8f5febf6783209c01d168cabe9bd061c9f2c#diff-da2056e2f7506fa2473f129c75717388 
thanks to betaflight
> fix as speed calculation for crsf telemetry

- src/main/target/MATEKF411SE/config.c
- src/main/target/MATEKF411SE/target.c
- src/main/target/MATEKF411SE/target.h
- src/main/target/MATEKF411SE/target.mk
coded and tested by PYRO just adding it for him
> adding MATEKF411SE

- src/main/target/IFF4_TWIN_G/IFF4_TWIN_G_M.mk
- src/main/target/IFF4_TWIN_G/target.h
- src/main/target/IFF4_TWIN_G/target.mk
- src/main/target/IFF7_TWIN_G/target.h
> fixing some minor stuff

- src/main/target/HGLRCF722/config.c
- src/main/target/HGLRCF722/target.c
- src/main/target/HGLRCF722/target.h
- src/main/target/HGLRCF722/target.mk
I want a cinewhoop :) just saying lol
> add HGLRCF722

- README.md
Changing filtering settings in DJI OSD can cause unusual config changes in emuflight
Examples are here...
Google docs link of my testing with DJI OSD: https://docs.google.com/spreadsheets/d/1MlzeTgJpdGB2y0S2GhVLUJf304ZfkVu2dAei0YrJhqU/edit?usp=sharing
I think adding this wording would be appropriate
> Update README.md with DJI OSD Compatibility info

- src/main/sensors/gyro_filter_impl.h
* enable feature DYNAMIC_FILTER for Helio/Strix/Mode2Flux
> Fix for dynNotch and staticNotch

- src/main/target/HGLRCF722/target.h
- src/main/target/HIFIONRCF7/config.c
- src/main/target/HIFIONRCF7/target.c
- src/main/target/HIFIONRCF7/target.h
- src/main/target/HIFIONRCF7/target.mk
- src/main/target/ZEEZF7/target.h
- src/main/target/ZEEZF7/target.mk
adding target, few minor fixes on older targets
> Hifionrc f722

- src/main/target/PYRODRONEF7/PYRODRONEF7.md
- src/main/target/PYRODRONEF7/config.c
- src/main/target/PYRODRONEF7/target.c
- src/main/target/PYRODRONEF7/target.h
- src/main/target/PYRODRONEF7/target.mk
Add PYRODRONEF7 target
New F7 2020 size from Pyrodrone
> add PYRODRONEF7

- src/main/flight/failsafe.c
- src/main/flight/failsafe.h
- src/main/io/osd.c
- src/test/unit/arming_prevention_unittest.cc
- src/test/unit/blackbox_unittest.cc
- src/test/unit/osd_unittest.cc
- src/test/unit/pid_unittest.cc
- src/test/unit/platform.h
- src/test/unit/telemetry_crsf_msp_unittest.cc
- src/test/unit/telemetry_crsf_unittest.cc
- src/test/unit/vtx_unittest.cc
Fixed some tests, removed extra spaces from altitude string on the osd screen.
> Fixed tests

- src/main/target/ZEEZF7/config.c
- src/main/target/ZEEZF7/target.h
- src/main/target/ZEEZWHOOP/target.c
- src/main/target/ZEEZWHOOP/target.h
- src/main/target/ZEEZWHOOP/target.mk
blackbox functionality is still being worked on atm, current state is working without blackbox
need drivers updated for the blackbox to work
> ZeezF7, Whoop

- src/main/target/FLYWOOF405/config.c
> Update config.c FLYWOOF405

- lib/main/STM32_USB_Device_Library/Class/msc/inc/usbd_msc_core.h
- lib/main/STM32_USB_Device_Library/Class/msc/src/usbd_msc_core.c
- lib/main/STM32_USB_OTG_Driver/src/usb_core.c
- src/main/build/atomic.h
- src/main/fc/fc_rc.c
- src/main/msc/usbd_msc_desc.c
- src/main/vcpf4/usbd_desc.c
went through a handful of the warnings, and fixed them. Removed a bit of unused code and fixed some problems with errors. Now compiling is cleaner.
> lots of warning fixes :)

- src/main/target/HGLRCF411/target.h
* enable flash as per @Kaiowarez
> HGLRCF411 enable flash

- src/main/flight/pid.c
* found by @Quick-Flash 
* correction as per @Quick-Flash
> dterm bugfix for angle-mode

- .github/workflows/build.yml
- .travis.sh
- .travis.yml
- Makefile
- make/targets.mk
* meh, can't we just let Travis die already?
> 4 parallel builds

- src/main/cms/cms_menu_imu.c
- src/main/interface/settings.c
* Atomic branch for OSD Advanced PID Menu
* filtered from DBoost branch
* requires testing
* merge before DBoost & iDecayV2
> OSD advanced pid menu

- src/main/target/FOXEERF722DUAL/target.h
- src/main/target/FOXEERF722DUAL/target.mk
* waiting on test results
* coded as per @Kaiowarez
> add FOXEERF722V2

- src/main/target/TALONF7V2/target.h
@kaiowarez fix TALONF7V2 vbat scale and default airmode
> TALONF7V2 vbat scale and default airmode

- src/main/target/FLYWOOF411/config.c
- src/main/target/FLYWOOF411/target.c
- src/main/target/FLYWOOF411/target.h
> fix FlywooF411 LED, etc

- src/main/target/MAMBAF405US/config.c
- src/main/target/MAMBAF405US/target.h
Fixed LED resource for Diat- MAMBAF405US
tested by Mike
> fix MAMBAF405US LED Resources

- src/main/target/JBF7/config.c
- src/main/target/JBF7/target.c
- src/main/target/JBF7/target.h
- src/main/target/JBF7/target.mk
> Adding target IFRC- JBF7 

- src/main/target/HGLRCF411/target.h
* modded as per @Kaiowarez request.
> fix HGLRCF411 softserial assignment

- src/main/target/SUCCEX_EF4/target.c
- src/main/target/SUCCEX_EF4/target.h
- src/main/target/SUCCEX_EF4/target.mk
> add Target SUCCEX E F4

- src/main/target/BETAFPVF405/target.h
> fixing BetafpvF405 target

- src/main/target/BETAFPVF411/target.c
- src/main/target/BETAFPVF411/target.h
- src/main/target/BETAFPVF411/target.mk
removing V3 tag. to avoid confusion
updated gyro config
> Fixing BetafpvF411

- src/main/target/AIRF7/config.c
- src/main/target/AIRF7/target.h
- src/main/target/AIRF7/target.mk
- src/main/target/CLRACINGF7/target.h
- src/main/target/FURYF4/target.c
- src/main/target/FURYF4/target.h
fixing AIRF7 gyro and accel resource
added clracingF7 pinio fix as well
FURYF4OSD added timer as per BF targets list update
> Fixed AIRF7, CLRACINGF7, FURYF4

- src/main/interface/settings.c
- src/main/io/osd.c
- src/main/io/osd.h
* code by @Kaiowarez 
* needs testing
> CRSF LQ modifiable blink level

- src/main/cms/cms_menu_imu.c
- src/main/interface/settings.c
* Do not allow Q <100
* tested CLI good
* did not test OSD configuring
> Minimum allowed IMUF Q 100

- src/main/target/DFRF722DUALHD/target.c
- src/main/target/DFRF722DUALHD/target.h
- src/main/target/DFRF722DUALHD/target.mk
Add a new target for the DFR F722 DUAL HD fc .
> Add New DFR F722 DUAL HD FC

- src/main/fc/fc_rc.c
Hi there, I noticed there was a flaw in the current implementation when I recently switched my racing whoops to redpine protocol (1.5ms latency) on my own betaflight fork with backported rate dynamics from emuflight.
Using the same rate profiles I used before on frsky d8 spi, rate dynamics felt like not working at all because the protocol latency was so low that RD was unnoticeable.
This PR makes rate dynamics feel the same regardless of the RX protocol refresh rate you are currently using. I made a web-based prototype before implementing this out, so you can check it out here: https://tth0v.csb.app/. Untick _RX Refresh Rate Invariant_ and set _RX rate_ to max to see how RX Rate affects rate dynamics. When ticking _RX Refresh Rate Invariant_, my current proposal will be active and the …
> fix: make rate dynamics feel the same regardless rx rate

- src/main/cms/cms_menu_osd.c
- src/main/interface/settings.c
- src/main/io/osd.c
- src/main/io/osd.h
> CRSF SIMPLE(0-100) & SCALE(170-300)

- src/main/target/TRANSTECF405HD/target.c
- src/main/target/TRANSTECF405HD/target.h
- src/main/target/TRANSTECF405HD/target.mk
> add target TRANSTECF405HD

- .github/workflows/build.yml
* build branches too
* will build branches on forks to assist devs (github actions)
* artifact_name (.zip) will be named based on emuflight or developer
> github workflow / buildtest branches too

- src/main/cli/cli.c
- src/main/drivers/pwm_output_dshot_hal.c
- src/main/drivers/pwm_output_dshot_shared.c
- src/main/drivers/pwm_output_dshot_shared.h
- src/main/msp/msp.c
This is the branch I have created so that we can "keep up with the Jonses". As betaflight updates I'll be cherry picking their code and periodically updating this. This is how we will keep up with betaflight. Don't delete this branch, it will be used for this purpose.
This merge includes:
https://github.com/betaflight/betaflight/pull/10408
https://github.com/betaflight/betaflight/pull/10407
> Keeping up with the joneses

- src/main/interface/settings.c
* modify naming after discussion with MrShutterbug and PJClarke
* `add_yaw_with_roll_input`-->addRollToYawRc (add yaw movement when roll stick)
* `add_roll_with_yaw_input`-->addYawToRollRc (add roll movement when yaw stick)
> modify DAS naming

- src/main/interface/settings.c
* make it easier to CLI `get das`
* `das_yaw_with_roll_input`
* `das_roll_with_yaw_input`
> mod DAS naming

- src/main/target/RUSHBLADEF7/target.h
* swapped `PA4` & `PC4` as per @Kaiowarez .
* reported working.
> RushBladeF7 fix as per Kaio

- src/main/cms/cms_menu_imu.c
uint16 where it should be a uint8 inside the osd menus.
> Fix ABG osd bug

- src/main/common/filter.c
ABG half life bug, this should fix half life.The divisor is wrong for the half life.
> fix half life

- src/main/target/KAKUTEF7MINIV3/target.c
- src/main/target/KAKUTEF7MINIV3/target.h
- src/main/target/KAKUTEF7MINIV3/target.mk
* pulled from @Kaiowarez 's branch `Kakutef7-Mini-V3`, @Fred29 reported working.
> kakute f7 mini v3

- src/main/common/maths.c
- src/main/common/maths.h
- src/main/fc/fc_rc.c
https://github.com/betaflight/betaflight/pull/10711
> Remove unneeded library function 'powerf()'

- src/main/telemetry/mavlink.c
https://github.com/mavlink/mavlink/issues/1027
> MavLink RSSI Range

- src/main/build/version.h
* bump version to differentiate for dev/testers 
* super close to 0.4.0
> bump version 0.3.6

- src/main/io/displayport_srxl.c
> EmuFlight in Spektrum CMS

- src/main/blackbox/blackbox.c
- src/main/cms/cms_menu_imu.c
* compiles
* needs test
* unsure if fits on OSD screen (historical issue)
> OSD and BB headers for dterm_dyn_notch_enable & dterm_dyn_notch_q

- src/main/flight/pid.c
* Fix DLPF2 filter-apply for PT2 PT3 PT4
> Fix DLPF2 filter-apply for PT2 PT3 PT4

- src/main/common/kalman.c
- src/main/sensors/gyro_filter_impl.h
* @Quick-Flash 's Kalman debug branch
* only on roll, maybe should not merge.
> Better kalman debugging

- src/main/flight/pid.c
* set 2PASS motor output mixer as default
> 2PASS motor output mixer as default

- src/main/build/version.h
* bump version 0.3.7
* for separation from from dev hex
> bump version 0.3.7

- src/main/blackbox/blackbox.c
* fix BBH for ` dynamic_gyro_notch_q`
> fix BBH for dynamic gyro notch q

- src/main/target/ZEEZ_ZEEZF7V2/target.c
- src/main/target/ZEEZ_ZEEZF7V2/target.h
- src/main/target/ZEEZ_ZEEZF7V2/target.mk
> add ZeezF7 v2

- src/main/target/TURC_FPVCYCLEF401/target.c
- src/main/target/TURC_FPVCYCLEF401/target.h
- src/main/target/TURC_FPVCYCLEF401/target.mk
* add target TURC_FPVCYCLEF401
* coded by @Kaiowarez 
* tested by @SkylionFPV
> add TURC_FPVCYCLEF401

- src/main/interface/msp.c
- src/main/interface/msp_protocol.h
* WIP; dev/testing in progress
* Requires new EmuConfigurator
MSP for new features:
* ABG gyro
* ABG dTerm
* Motor Mixer / Linearizations / yawFix
* df_yaw
* emuGravity
* Axis Lock
* Fast SBUS
* rc rates type
* smith on/off toggle
* removed SDS, WC
Requires https://github.com/emuflight/EmuConfigurator/pull/386
> MSP 1.51 for 0.4.0

- src/main/build/version.h
> bump version 0.4.0

- src/main/io/serial_4way.c
Reservation of an MCU_ID area to simplificate adding of upcoming BLHeli_32 MCU
> Update serial-4way-if to v20005

- src/main/target/IFF4_E/target.h
- src/main/target/IFF4_E/target.mk
https://github.com/emuflight/EmuFlight/issues/677
> [IFF4_E] Add BMP280 Baro Support

- src/main/target/HOWI_HOBBYWING_XROTORF7CONV/target.c
- src/main/target/HOWI_HOBBYWING_XROTORF7CONV/target.h
- src/main/target/HOWI_HOBBYWING_XROTORF7CONV/target.mk
needs testing sending to ill bro
1. Pull requests will only be accepted if they are opened against the `master` branch. Pull requests opened against other branches without prior consent from the maintainers will be closed;
2. Please follow the coding style guidlines: https://github.com/emuflight/EmuFlight/blob/master/docs/development/CodingStyle.md
3. Keep your pull requests as small and concise as possible. One pull request should only ever add / update one feature. If the change that you are proposing has a wider scope, consider splitting it over multiple pull requests. In particular, pull requests that combine changes to features and one or more new targets are not acceptable.
4. Ideally, a pull request should contain only one commit, with a …
> add target HOWI_HOBBYWING_XROTORF7CONV

- src/main/target/DAFP_DARWINF722HD/config.c
- src/main/target/DAFP_DARWINF722HD/target.c
- src/main/target/DAFP_DARWINF722HD/target.h
- src/main/target/DAFP_DARWINF722HD/target.mk
* Tested with feedback on 3 different builds by Kabab FPV. Orientation, motors, DJI setup, ADC, BlackBox, all work great. 
* https://github.com/emuflight/EmuFlight/issues/708
* recommend merge
> Target Build DAFP_DARWINF722HD

- src/main/target/FLWO_FLYWOOF411FR/target.c
- src/main/target/FLWO_FLYWOOF411FR/target.h
- src/main/target/FLWO_FLYWOOF411FR/target.mk
- Tested on one build so far. Motors, board orientation, flying, OSD, IRC Tramp (both OSD and CLI), ADC, connection to external receiver, have all tested good. 
- https://github.com/emuflight/EmuFlight/issues/726
- Recommend merge
> Target Build FLWO_FLYWOOF411FR

- src/main/target/NBDBBBLV2/target.h
- src/main/target/NBDBBBLV2/target.mk
Redpine added to NBDBBBLV2 target. Waiting for response from tester to see if works.
> Add Redpine to NBDBBBLV2

- src/main/target/NBDHMBF41S/target.h
- src/main/target/NBDHMBF41S/target.mk
Updating all SPI_FRSKY boards to have Redpine
> ADD REDPINE TO NBDHMBF41S

- src/main/target/BEEBRAIN_PRO/target.h
- src/main/target/BEEBRAIN_PRO/target.mk
Updating all SPI_FRSKY boards to have Redpine
> ADD REDPINE TO BEEBRAIN_PRO

- src/main/target/BETAFPVF411RX/target.c
- src/main/target/BETAFPVF411RX/target.h
- src/main/target/BETAFPVF411RX/target.mk
Tested and flies with external spi reciever. Multiple good reports.
https://github.com/emuflight/EmuFlight/issues/486
Merge to Master
> TARGET BETAFPVF411RX

- src/main/target/EMAXF411/config.c
- src/main/target/EMAXF411/target.c
- src/main/target/EMAXF411/target.h
- src/main/target/EMAXF411/target.mk
Thoroughly tested and fixed with great results.
https://github.com/emuflight/EmuFlight/issues/533
Merge to master
> Target EMAXF411

- src/main/target/AIRBOTF7HDV/config.c
- src/main/target/AIRBOTF7HDV/target.c
- src/main/target/AIRBOTF7HDV/target.h
- src/main/target/AIRBOTF7HDV/target.mk
Ready to merge to master.
Tested with functioning features (after I fixed gyro code).
https://github.com/emuflight/EmuFlight/issues/697
> Target: AIRB_AIRBOTF7HDV

- .github/workflows/build.yml
- Makefile
* GitHub Actions workflow for building and releasing (same tag-building system we already use)
* Makefile forkname EmuFlight
* Makefile for Commit-SHA and uncommitted in hex filename
> 1.0.0 GitHub actions workflow

- src/main/target/TMOTORF7V2/config.c
- src/main/target/TMOTORF7V2/target.c
- src/main/target/TMOTORF7V2/target.h
- src/main/target/TMOTORF7V2/target.mk
Target Request: `TMOTORF7V2`
See Issue: https://github.com/emuflight/EmuFlight/issues/629
Bluetooth works and firmware is flyable. @madchiller for more testing
> Target TMOTORF7V2

- src/main/target/MATEKF722HD/target.h
Merge if approved
See issue https://github.com/emuflight/EmuFlight/issues/776
Fixed file and was tested by myself and pilot.
> Fix UART duplication/count on MATEKF722HD

- src/main/target/AXISFLYINGF7/target.c
- src/main/target/AXISFLYINGF7/target.h
- src/main/target/AXISFLYINGF7/target.mk
From target build https://github.com/emuflight/EmuFlight/issues/780
Testing checks out and flies great. 
Merge if approved.
> Target AXISFLYINGF7

- src/main/target/TMTR_TMVELOX/config.c
- src/main/target/TMTR_TMVELOX/target.c
- src/main/target/TMTR_TMVELOX/target.h
- src/main/target/TMTR_TMVELOX/target.mk
Merge-able if approved.
Flies great and bluetooth works for all the testers that use this fw for the TMotor Velox FC, as opposed to TMotorF7V2. 
See https://github.com/emuflight/EmuFlight/issues/745
> Target - TMVELOX

- src/main/io/serial_4way.c
* port [widening range of BLHeli/_S device id #11513](https://github.com/betaflight/betaflight/pull/11513)
* needs testing
> port "widening range of BLHeli/_S device id BF#11513"

- src/main/target/ZEUSF722_AIO/config.c
- src/main/target/ZEUSF722_AIO/target.c
- src/main/target/ZEUSF722_AIO/target.h
- src/main/target/ZEUSF722_AIO/target.mk
Tested per https://github.com/emuflight/EmuFlight/issues/525
Closes #525
> TARGET ZEUS722_AIO

- src/main/target/GEPRCF405/config.c
- src/main/target/GEPRCF405/target.c
- src/main/target/GEPRCF405/target.h
- src/main/target/GEPRCF405/target.mk
Tested per https://github.com/emuflight/EmuFlight/issues/628
Closes #628
> TARGET GEPRCF405

- src/main/target/RUSH_BLADE_F7_HD/target.c
- src/main/target/RUSH_BLADE_F7_HD/target.h
- src/main/target/RUSH_BLADE_F7_HD/target.mk
Tested per https://github.com/emuflight/EmuFlight/issues/694
Closes #694
> TARGET RUSH_BLADE_F7_HD

- src/main/target/LDARC_F411/target.c
- src/main/target/LDARC_F411/target.h
- src/main/target/LDARC_F411/target.mk
Test good per https://github.com/emuflight/EmuFlight/issues/722
Closes #722
> Target LDARC_F411

- src/main/target/ZEUSF4FR/target.c
- src/main/target/ZEUSF4FR/target.h
- src/main/target/ZEUSF4FR/target.mk
Tested Per https://github.com/emuflight/EmuFlight/issues/734
Closes #734
> Target ZEUSF4F4

- src/main/target/FOXEERF745_AIO/target.c
- src/main/target/FOXEERF745_AIO/target.h
- src/main/target/FOXEERF745_AIO/target.mk
Tested per https://github.com/emuflight/EmuFlight/issues/752
Closes #752
> Target FOXEERF745

- src/main/target/IFLIGHT_BLITZ_F405/target.c
- src/main/target/IFLIGHT_BLITZ_F405/target.h
- src/main/target/IFLIGHT_BLITZ_F405/target.mk
Tested per https://github.com/emuflight/EmuFlight/issues/764
Closes #764
> TARGET IFLIGHT_BLITZ_F405

- src/main/target/GEPRCF411_AIO/target.c
- src/main/target/GEPRCF411_AIO/target.h
- src/main/target/GEPRCF411_AIO/target.mk
Tested per https://github.com/emuflight/EmuFlight/issues/766
Closes #766
> TARGET GEPRCF411_PRO

- src/main/target/ZEUSF4EVO/target.c
- src/main/target/ZEUSF4EVO/target.h
- src/main/target/ZEUSF4EVO/target.mk
Tested per https://github.com/emuflight/EmuFlight/issues/777
Closes #777
> TARGET ZEUSF4EVO

- src/main/target/JHEMCUF405/target.c
- src/main/target/JHEMCUF405/target.h
- src/main/target/JHEMCUF405/target.mk
Tested per https://github.com/emuflight/EmuFlight/issues/799
Closes https://github.com/emuflight/EmuFlight/issues/799
> TARGET JHEMCUF405

- src/main/target/HAKRCF722D/config.c
- src/main/target/HAKRCF722D/target.c
- src/main/target/HAKRCF722D/target.h
- src/main/target/HAKRCF722D/target.mk
Tested per https://github.com/emuflight/EmuFlight/issues/806
Closes https://github.com/emuflight/EmuFlight/issues/806
> TARGET HAKRCF722D

- src/main/target/GEPRCF722BT/config.c
- src/main/target/GEPRCF722BT/target.c
- src/main/target/GEPRCF722BT/target.h
- src/main/target/GEPRCF722BT/target.mk
Tested per https://github.com/emuflight/EmuFlight/issues/723
Closes #723
> TARGET GEPRCF722BT

- src/main/target/AOCODAF722MINI/target.c
- src/main/target/AOCODAF722MINI/target.h
- src/main/target/AOCODAF722MINI/target.mk
Target for `AOCODAF722MINI` per https://github.com/emuflight/EmuFlight/issues/793
Tested by Skylion
Merge if approved.
Closes https://github.com/emuflight/EmuFlight/issues/793
> TARGET-AOCODAF722MINI

- src/main/target/DFRF722DUALHD/target.h
* as per https://github.com/emuflight/EmuFlight/pull/712#pullrequestreview-812075900
* verified via unified-targets
> DFRF722DUALHD define gyro 2 pin correctly

- src/main/blackbox/blackbox.c
* add rates_type to BBL header
* this is why EmuBBE fails to render actual/kiss properly
> add rc rates_type to BBL header

- src/main/blackbox/blackbox.c
- add motor_poles to BBL header
> add motor_poles to BBL header

- src/main/target/SKYSTARSF7HDPRO/config.c
- src/main/target/SKYSTARSF7HDPRO/target.c
- src/main/target/SKYSTARSF7HDPRO/target.h
- src/main/target/SKYSTARSF7HDPRO/target.mk
Co-authored-by: nerdCopter <56646290+nerdCopter@users.noreply.github.com>
> [target] SKYSTARSF7HDPRO

- src/main/target/NBD_INFINITYAIOV2/target.h
- don't count non-defined UARTS
> [target] NBD_INFINITYAIOV2 (non-pro) fixup

- src/main/target/NERO/target.c
- src/main/target/NERO/target.h
- src/main/target/NERO/target.mk
- **[target] update NERO**
- thanks to @ahmad-kassem for updating Betaflight unified-target
> [target] update NERO

- src/main/target/EACHINEF722/target.c
- src/main/target/EACHINEF722/target.h
- src/main/target/EACHINEF722/target.mk
> [target] add EACHINEF722

- src/main/sensors/acceleration.c
This reverts commit bf2153163cdb6edbb1e4c83e5fc048f43c34f53b.
> Revert "fix compiler warnings for ACC_2_ALIGN identical branches (#1051)"

- src/main/target/JHEF745/target.c
- src/main/target/JHEF745/target.h
- src/main/target/JHEF745/target.mk
removed motor 7 & 8 as no associated timers defined.
> [target] add JHEF745

- src/main/target/JHEF745/target.h
> [target] JHEF745 dshot_burst ON by default

- src/main/target/TMOTORF7/target.c
- src/main/target/TMOTORF7_AIO/target.c
[EmuFlight_0.4.3_TMOTORF7_TimerFix.zip](https://github.com/user-attachments/files/17195579/EmuFlight_0.4.3_TMOTORF7_TimerFix.zip)
> [targets] TMOTORF7 / TMOTORF7_AIO - fix motor3 timer/channel

- src/main/target/NBD_INFINITYAIO255/target.c
- src/main/target/NBD_INFINITYAIO255/target.h
- src/main/target/NBD_INFINITYAIO255/target.mk
- resolves https://github.com/emuflight/EmuFlight/issues/1079
- needs testing
> [target] add NBD_INFINITYAIO255

- src/main/target/FREEAXISF4/target.c
- src/main/target/FREEAXISF4/target.h
- src/main/target/FREEAXISF4/target.mk
- https://www.freeaxis.net/archives/f4-aio-12a-elrs
[EmuFlight_0.4.3_FREEAXISF4_Build_179c0bb86.hex.zip](https://github.com/user-attachments/files/16414014/EmuFlight_0.4.3_FREEAXISF4_Build_179c0bb86.hex.zip)
> [target] FREEAXISF4 (F411)
