emuflight/EmuFlight

src/main/flight/position.c
src/main/telemetry/crsf.c

From 22/07/2018 until the release of Betaflight 3.5.0 (scheduled for 05/08/2018), the project is in a 'feature freeze / release candidate' phase. This means:
1. Pull requests can still be submitted as normal. Comments / discussions will probably be slower than normal due to shifted priorities;
2. If your pull request is a fix for an existing bug, or an update for a single target that has a low risk of side effect for other targets, it will be reviewed, and if accepted merged into `master` for the 3.5 release;
3. All other pull requests will be scheduled for 4.0, and discussed / reviewed / merged into `master` after 3.5.0 has been released. Please keep in mind that this potentially means that you will have to rebase your changes if they are broken by bugfixes made for 3.5.
1. Pull requests …

Updating crossfire telemtry and use fonction prom position

---

src/main/blackbox/blackbox.c
src/main/flight/mixer.c
src/main/flight/mixer.h
src/main/flight/pid.c
src/main/flight/pid.h

Add setpoints to blackbox logging
Full credit to etracer65 : https://github.com/betaflight/betaflight/commit/99685c21c62fdf7ce23ac3d9ce6dea995cbadef4#diff-c5f9576172e273033324ba218524cc97
This records actual setpoint values for each axis as used by the PID controller in blackbox data logs.
This allows the new PID Error VS Setpoint graph of BBE 3.5.0 to work with EmuFlight blackbox logs. https://github.com/betaflight/blackbox-log-viewer/pull/416

Add setpoints to blackbox logging [credit to etracer65]

---

src/main/interface/settings.c
src/main/sensors/current.c
src/main/sensors/voltage.c
src/main/sensors/voltage.h

I really like the way how betaflight 4.0 current and voltage are really "jumpy". On punchouts the displayed current value will be more close to the truth and during hangtime you can estimate your current battery voltage without sag.
In BF this was introduced in:
betaflight/betaflight#7447 +(betaflight/betaflight#7546)
However, I do not know how you handle porting Betaflight features into EmuFlight. 
- Will you copy features from BF one by one into EmuFlight when they are needed or wanted? (like this PR)
- Or will you some day rebase all the EmuFlight features on top of bf 4.x ?

Make battery voltage / current filter cutoffs configurable - Policy on Betaflight features

---

src/main/drivers/max7456_symbols.h
src/main/io/osd.c

Requires v2 fonts uploaded to flight controller.  GUI will trigger v2 font usage with msp 1.44+
Not only fixes crosshair, but also includes some GPS, temperature, and imperial/metric character fixes.

Use v2font msp 1.44+ [skip ci]

---

src/main/common/filter.c

For unknown reason `filterGetNotchQ` was returning a constant Q factor that:
* happily ignored notch filter cutoff frequency
* that was leading to a situation when cutoff (-dB) was approx. center/2 (always)
* phase delay was not constant but was growing  with center frequency as attenuated band was wider and wider

fix filterGetNotchQ

---

src/main/common/filter.c
src/main/common/filter.h

Remove the lagging average filter which is no longer used.
This filter has not been used for quite a long time as far as I am aware. No need to keep bloat in the code.

remove lagging average filter from code

---

src/main/cms/cms_menu_imu.c
src/main/interface/msp.c
src/main/interface/settings.c
src/main/sensors/gyro.c
src/main/sensors/gyro.h
src/main/sensors/gyro_filter_impl.h

The GA or gyro average filter was adopted from the old RaceFlightOne code and has not shown itself to be useful. So this filter is being removed in light of simplification and progression. Should make configurator changes easier as well.

Remove GA Filter

---

src/main/flight/mixer.c
src/main/flight/mixer.h
src/main/flight/pid.c
src/main/interface/settings.c

Before the old turtle mode code would only allow for about 70% power when attempting a pitch or a roll movement, but 100% power when spinning a corner motor or doing a yaw. Now its been changed so that motors can only have at max the power level you configure. Default value is 70 to help with safety and motor burning. These values can be increased for whoops and decreased for some craft that are quite powerful. Should make turtle mode overall a little bit better. A wiki write up should accompany this update as well.
Was looking at this code when trying to figure out how I wanted to approach cinematic setpoint and it bugged me enough I dropped this quick fix.

make turtle mode power output configurable

---

src/main/interface/settings.c
src/main/sensors/gyro.c
src/main/sensors/gyro.h
src/main/sensors/gyroanalyse.c
src/main/sensors/gyroanalyse.h

Gyroanalyse quality factor (?) seemed to work with a very peculiar way:
* it was setting a BPF and center on `fftSamplingRate / 4`
* default Q factor of `0.7` was setting cutoff at approx half of this frequency. Lowering to somewhere recommended `0.1` was setting to approx. 10% of it
As a result:
* gyroanalyse was preferring frequencies closer to `fftSamplingRate / 4` more than any other frequencies
* peak detection was not constant among frequency range
* tuning of this factor was bound to fftFrequency that is not visible to the user and not even directly dependent on looptime frequency
* in general, hard to use, complicated, with questionable gain and apparently useless on a longer run
This PR is an addition to #110

Drop gyroanalyse quality factor

---

src/main/common/kalman.c

@DzikuVx showed me a potential bug within the kalman.c code. Right now setpoint[axis] is called but never initialized or set to anything. It appears that it never updates nor does anything. This code should update it to properly store the correct setpoint with every kalman update. I'd like this to be looked into more though, because I have logged the kalman before and seen it do things, but now that I've looked at it again I am pretty sure that setpoint within kalman.c currently does nothing.
Thanks for pointing this out Pawel :)

Fix a bug in kalman.c?

---

src/main/target/common_fc_pre.h

Define USE_PEGASUS_UI in order to help with further gui development. It adds a cli command that dumps every single setting on your quad. The command is config and it lists every single configurable setting for your drone. Hoping that it can help manage some of the MSP complexity that plagues us.

USE_PEGASUS_UI

---

src/main/build/debug.c
src/main/build/debug.h
src/main/common/kalman.c
src/main/flight/pid.c

adds a debug that shows what the dterm is multiplied by. It shows it multiplied by 1000 though, so if smart smoothing shrinks your dterm by half it will show 500. If it leaves the dterm untouched it will show 1000. Just a way to make this easier to see in a bbl.
this should make it easier to see what the debug mode is doing to help us better understand it and see how to tune it.

debug for smart smoothing

---

src/main/rx/cc2500_frsky_shared.c
src/main/rx/cc2500_frsky_x.c

I'm hoping this fixes d16 mode on the EMAX "d8-compatible" tinyhawk. (works in emuflight 4, but not in emuflight 3 or betaflight)
----- 
Original fix into betaflight here -- https://github.com/betaflight/betaflight/pull/7345/
Original merge into emuflight here -- https://github.com/emuflight/EmuFlight/commit/c3521db8f13896b9e1c599439ed42e05ef089b25#diff-8d164ba28d885dd7f800306523978b00
It appears to have been (accidentally?) undone in a subsequent commit here -- https://github.com/emuflight/EmuFlight/commit/089283648cae4cc5dab1294590c649e260ccb5d8#diff-8d164ba28d885dd7f800306523978b00
So this MR simply re-does the original fix over the top of EF's latest master.

reapply betaflight -- ignore failsafe packets in rx_spi_frskyx #7345

---

src/main/cms/cms_menu_imu.c
src/main/fc/controlrate_profile.c
src/main/fc/controlrate_profile.h
src/main/flight/mixer.c
src/main/flight/pid.c
src/main/flight/pid.h
src/main/interface/msp.c
src/main/interface/settings.c
src/main/sensors/battery.c
src/main/sensors/battery.h

Resuming a PR I screwed-up with (git rebasing gone wrong).
This PR is intended to port thrust linearization to EmuFlight. Something like betaflight/betaflight#7304, using a different, simpler, formula to compensate thrust non-linearity.
Thrust/RPM relationship is similar to a quadratic curve, but not exactly equal. A configurable mix with a linear relationship (no compensation) is used to find the exact compensation for a given quad.
Efficient quads (motor, propellers etc) will have a thrust_linearization_level close to 100, whereas a less efficient one will have a lower level, something like 65.
throttle_linearization is a boolean parameter that tells if the throttle feel has to be "linear" or de-compensated to match the old fashioned square root feel (default value).
I found the linear …

thrust linearization

---

src/main/blackbox/blackbox.c

adding rate dynamics
fixing how levelPIDHIGH is displayed
adding witchcraft
adding smart_smoothing
adding IMUF_sharpness
All of these things are now shown in blackbox logs when you decide to look at them. Just have to press h and you should see them show up once you scroll all the way down.

Making BBL show logs more completely

---

src/main/flight/pid.c

previousPidSetpoint[axis] is used in blackbox logging to log your current setpoint. However when feedforward was removed this was also removed, and the unintended consequence was that logs of setpoint were no longer quite accurate. This should fix that and hopefully fix an issue with logging.
this is what we want to see 
instead this is what we see 
Rate Dynamics is not getting logged properly and is making the quad look sporadic in how it handles error. Looks actually very very bad. However if you look at pitch on the second image you can easily see that a lot of that pitch error comes from doing backflips while using rate dynamics.

Fix bug with logging.

---

src/main/blackbox/blackbox.c

Added following fields to be logged with blackbox logs:
nfe_racermode
iterm_rotation
throttle_boost
This will help to show the status of above mentioned fields on tuninghub.net or anyone who'd like to access it from the log file.

Added some missing fields to blackbox logs

---

src/main/interface/settings.c

* limit `rate_center_correction` & `rate_end_correction` minimum to `10`
as per @Quick-Flash

rateDynamics correction minimum 10

---

src/main/flight/mixer.c

since changing turtle mode it appears that turtle mode has less power than it did before. This fixes that issue and restores the power that turtle mode should have. (this bug was found as more whoop pilots had issues in turtle mode)

Fix turtle power

---

src/main/flight/pid.c

This code makes smart smoothing smoother. It makes the transition multiplier that smart smoothing applies to the dterm more smooth. Before it would go from a multiplier of .5 to greater very very quickly. This change will make the transition from .5 multiplier to a multiplier of 1 far smoother.
This PR also takes the default smart smoothing and sets it to 0.

update to smart smoothing

---

make/tools.mk

windows arm_sdk download was wrongly named with .bz2 extension, changed to .zip

fix ./make/tools.mk for windows

---

src/main/build/version.h

The Hex code is ready, Keep this branch so that we have a version of the 0.3.0 code that is easy to find. Will be useful for adding new targets and for keeping a history. 
This code just pushes the version numbering to 0.3.0

Update version.h for the release of 0.3.0

---

src/main/build/version.h

* This is equivalent to Travis Build 747
* KakuteF7mini #219
* minor fix TmotorF4HD, adding target RACEPIT mini #217
* Flywoof405 #218
* informative .hex names #216
* 20200507 kalman covar without cross influence #213
* make the pid calculation nondynamic #212
* rename target NOX to NOXF4 #209

version bump 0.2.53

---

.github/workflows/build.yml

* 6 hour timeout too long for failure; 1hr 15min should be appropriate (75 minutes)
* jobs usually take about 45min currently for 155 targets

reduce build timeout

---

src/main/flight/position.c
src/main/interface/msp.c

revert an old change that was incorrect in position.c 
and dji is getting from msp_altitude the getestimatedalt only for USE_BARO or USE_RANGEFINDER 
i added USE_GPS so it is enable for all fc without BARO using GPS

fix alti for dji and fc whitout baro

---

src/main/target/NBDHMBF41S/target.h

Hi:
I test NewBeeDrone hummingbirdF4 brushless use the emuflight hex file, find the bind pin can't work. This pull request fix this bug.

fix rx bind pin not work

---

src/main/flight/gps_rescue.c

Fixes a typo in the GPS rescue altitude controller. It makes a huge difference, especially in the initial climb to the RTH altitude. Before it was overshooting every time, after the fix, the throttle is managed way smoother. Same as: betaflight/betaflight#7884

Fix GPS Rescue throttle PID calculation

---

.github/workflows/build.yml
Makefile

* Builds for PR tests as usual.
* Creates Draft-Release for tags, and uploads *.hex Assets
* We can manually delete Drafts as necessary
* For actual releases, we modify the Release-Notes and the tag to an `X.Y.Z` version
Easy to build master or any branch with something like:
(where `buildTag` is somewhat descriptive because it twill be used for draft notes and bintray)
```
git checkout [BRANCH]
git tag buildTag
git push [upstream|origin] buildTag
git tag --delete buildTag
git push --delete [upstream|origin] buildTag
```

github actions workflow for Draft Release

---

.github/workflows/build.yml
make/tools.mk

minor bump. compiles fine for me.
```
Release notes for
****************************************************
GNU Arm Embedded Toolchain 2020-q2-update
****************************************************
This release includes bare metal pre-built binaries for AArch32 EABI targets,
which can be hosted on:
* Windows 10 or later on 32/64-bit architecture
* Linux
- on AArch64 (RHEL 7, Ubuntu 14.04 or later)
- on x86_64 (RHEL 7, Ubuntu 16.04 or later)
* Mac OS X 10.14 or later on 64-bit architecture
For Windows, the binaries are provided with an installer and as a zip file.
For Linux, the binaries are provided as tarball files.
For Mac OS X, the binaries are provided as tarball and pkg files.
The release also contains source code package (together with build scripts and
instructions to setup …
```

upgrade toolchain to '2020-q2-update'

---

src/main/flight/pid.c

* revert to dTerm LPF1 cutoff `65` and LPF2 `200` for safety reasons
* pilots can tune as needed

revert to old dTerm LPF cutoffs

---

src/main/drivers/accgyro/accgyro_spi_icm20689.c
src/main/drivers/accgyro/accgyro_spi_mpu6000.c
src/main/drivers/accgyro/accgyro_spi_mpu9250.c
src/main/drivers/bus_spi.h

* replace misspelled `SPI_CLOCK_INITIALIZATON` with `SPI_CLOCK_INITIALIZATION`
* allows for further driver updates

SPI_CLOCK_INITIALIZATION spellcheck

---

src/main/cms/cms_menu_osd.c
src/main/interface/settings.c
src/main/interface/settings.h
src/main/io/osd.c
src/main/io/osd.h
src/main/rx/crsf.c
src/main/rx/rx.c
src/main/rx/rx.h

adding an option for for diffrent LQ formats
`osd_lq_format = TBS` (default) shows `LQ 300` style
`osd_lq_format = MODE` shows mode:LQ (e.g. `2:100`)
`osd_lq_format = FREQ` shows freq:LQ (e.g. `150HZ:100`)

CRSF LQ OSD Style options

---

src/main/target/SPEEDYBEEF7V2/config.c
src/main/target/SPEEDYBEEF7V2/target.c
src/main/target/SPEEDYBEEF7V2/target.h
src/main/target/SPEEDYBEEF7V2/target.mk

Hello,
We are going to release a new F7 flight controller, the following info is the main spec:
MCU: F722
GYRO: MPU6000
FLASH: 16MB flash
ESC POWER SUPPLY: NO
UART: 5 FULL UART and 1 UART RX for ESC Telemetry.
BEC: 5V & 9V BEC
There are some presets in the firmware defs:
1. This FC will have a combo with our BLHELI32 45A ESC, so we add some preset for the ESC, the presets are include
a. enable ESC_SENSOR
b. use DSHOT600 as default ESC protocol
c. turn on the "ESC" function on the UART4
2. Use SBUS as our default RX protocol, and in our recommended wiring diagram is use SBUS as our default RX device. 
Thanks for your review!

add speedybeef7v2

---

src/main/drivers/serial_uart_stm32f30x.c
src/main/drivers/serial_uart_stm32f7xx.c

All credit goes to @tonycake for fixing this.
This is an awesome fix. I personally experience this bug on one of my quads with FPORT receiver (and MatekF722-STD FC).
Sometimes when plugging the quad in, telemetry does not come through. I have to turn it off and on again, even multiple times.
I've just tested this change and telemetry on FPORT is now rock solid. Comes through every single time the quad powers up. 🎉 
**Copy of message from betaflight pr:**
Fix the issue described in Issue #10220, typos in serial drivers for F7, F3, G4, H7 platforms.
Before this change, the serial line is incorrectly pulled down for bidirectional comms, which may cause dropped packets (silently) with any Rx protocol that uses bidirectional comms on the Tx line (GHST, SRXL-2, FPORT)
Issue this addresses: …

FPORT fix: port of Betaflight https://github.com/betaflight/betaflight/pull/10388

---

src/main/rx/cc2500_frsky_d.c
src/main/rx/cc2500_frsky_shared.c
src/main/rx/cc2500_frsky_shared.h
src/main/rx/cc2500_frsky_x.c

Betaflight recently fixed a bug in frsky_d16 mode for SPI based recievers. The bug caused random drop out even in short range.
This is a port of 2 commits from betaflight:
https://github.com/mikeller/betaflight/commit/cb66ee09ba56a5f52f3355a404b43bbd3b7f0ec4
and one to fix lockups in frsky_x mode:
https://github.com/mikeller/betaflight/commit/77eb4f217272f9febeaa2dd5bec5b74060b407f7
All credit goes to @mikeller and @kevindehecker
Tested on Tinyhawk2 MATEKF411RX target.

Fix FrSky SPI receiver range and lockups

---

src/main/telemetry/crsf.c

```report_cell_voltage``` is not used currently for crossfire. This request fixes it.
Issue: #445

Avarage cell voltage for CSRF

---

src/main/blackbox/blackbox.c
src/main/cms/cms_menu_imu.c
src/main/common/maths.h
src/main/fc/config.c
src/main/fc/fc_core.c
src/main/fc/rc_modes.h
src/main/fc/runtime_config.h
src/main/flight/pid.c
src/main/flight/pid.h
src/main/interface/msp.c
src/main/interface/msp_box.c
src/main/interface/settings.c
src/main/io/osd.c

Adding NFE mode as a switch as well as making the logic for horizon mode better so that its harder for users to implement bad settings.

NFE as a switch

---

src/main/interface/cli.c
src/main/io/vtx_control.c
src/main/io/vtx_control.h
src/test/Makefile
src/test/unit/cli_unittest.cc
src/test/unit/vtx_unittest.cc

Backported from Betaflight: Adds an option to change vtx power with an aux channel.
more info on usage:
https://github.com/betaflight/betaflight/wiki/VTX-CLI-Settings
Example cli settings:
```
#channels on a 6 pos switch
vtx 0 7 5 1 0 900 1100
vtx 1 7 5 2 0 1100 1300
vtx 2 7 5 3 0 1300 1500
vtx 3 7 5 4 0 1500 1700
vtx 4 7 5 6 0 1700 1900
vtx 5 7 5 8 0 1900 2100
#vtx power on a 2 pos switch
vtx 6 6 0 0 1 900 1200
vtx 7 6 0 0 2 1800 2100
```
thanks @Quick-Flash  and @nerdCopter for help! 
This was was tested on Tinyhawk2 board (matekf411rx target) and works perfectly.
To test this, flash your FC with the build.
Setup a switch to control a spare Aux Channel on the radio.
Run the following commands in cli:
```
vtx 1 6 0 0 1 900 1200
vtx 2 6 0 0 2 1800 2100
```
The above uses AUX7 ( channels …

enhancement: CLI: allow vtx power to be changed by a switch

---

src/main/target/SPEEDYBEEF7V2/target.c

Hi,
this PR fixes the motor 4 can't spinning issue on SPEEDYBEE F7 V2, sorry about that, we have not run a real flight in emu flight before we submit a new target. We assumed the timer, DMA setting defines work on Betaflight, it will work on Emuflight as well, but it is not.

fix motor 4 can not spinning issue for SPEEDYBEE F7 V2

---

src/main/flight/pid.c
src/main/flight/pid.h
src/main/interface/settings.c

filters the setpoint which angle mode creates for the rate pid controller. Should lead to smoother angle mode. Has been tested by PJC and should be good to be merged. Should really be mostly an under the hood thing.

Add angle mode filtering

---

Makefile

Specify `uncommitted+YYYYMMDD` when building uncommitted source-code, otherwise same as before (`Build_####_SHA`)
* uncommitted: `EmuFlight_0.3.3_STRIXF10_Build_uncommitted_20210312CDT.hex`
* normal `EmuFlight_0.3.3_STRIXF10_Build_5a995933f.hex`
* i wanted time as well, but filename length caused error. did include Timezone which can estimate who might have compiled.

specify "uncommitted" in .hex & .bin when applicable

---

src/main/telemetry/crsf.c

Improve Crossfire telemetry flight modes to match Betaflight and INAV.
This matches the pull request I created for INAV and Betaflight here:
https://github.com/iNavFlight/inav/commit/c0964cbb2cf15d878fa6b57efe45ef2a3a96e9ad#diff-5b4ded67d6b41332a7188e3100bec940e517ea32550f01e25709b13f86eabc77
https://github.com/betaflight/betaflight/commit/4d8bf61d94614f20ff8ace847b5d2b12d8710bdf#diff-5b4ded67d6b41332a7188e3100bec940e517ea32550f01e25709b13f86eabc77
It not only provides additional telemetry flight information, it also allows compatibility with [LuaTelemetry](https://github.com/teckel12/LuaTelemetryINAV).  Feature requested by @Xedos9er https://github.com/teckel12/LuaTelemetryINAV/issues/442
This is **UNTESTED** as I don't fly EmuFlight.

Improved CRSF flight mode reporting.

---

src/main/target/XILOF4/target.h
src/main/target/XILOF4/target.mk

Enable the SPI gyro and fix the XILOF4 target.

Fix the XILOF4 NO_GYRO problem.

---

src/main/sensors/gyro_filter_impl.h

Gyro ABG filter was initialized previously, but it was never actually applied, this fixes that. Seriously check the code, gyroABGFilterApplyFn is never used up until I add it here. UGHGHGHGH. This code will work though, been tested on 1.0.0 (and yes it is initialized there). This should be merged asap there is no reason to wait on it.

Gyro ABG filter apply

---

src/main/blackbox/blackbox.c

* added gyroABG and dtermABG values to BBL header

BBL headers for ABG

---

src/main/blackbox/blackbox.c
src/main/cms/cms_menu_imu.c
src/main/flight/mixer.c
src/main/flight/pid.c
src/main/flight/pid.h
src/main/interface/settings.c

* needs code review for if a good `mixer.c` logic or not
* enabled by default.
* OSD PID>Advanced>`MIXER YAW THR COMP`.
* CLI `set mixer_yaw_throttle_comp = `.
* includes blackbox header.
* test hovered good on/off.
* OSD works
* CLI works

toggle for yaw-throttle-correction (compensation) PR#502

---

src/main/build/version.h

* i think it appropriate to bump version to 0.3.4 since we released 0.3.4
* should avoid confusion for next test-builds

bump version 0.3.5

---

.github/workflows/build.yml

* All tags build to GH-Actions artifacts.
* Tag names containing substring `releas` will draft-release to `emuflight` repo.
* Tag names containing substring `unstab` or `test` will draft-release to `dev-unstable` repo.
* Tag names containing substring `master` will draft-release to `dev-master` repo.
* tag could potentially contain all of the above substrings for draft-release to multiple repos.
* Removes defunct JFrog BinTray uploading.
* Disable building all branches (now requires tagging)
* Forks can use tags as well for personal repo gh-actions artifacts.
* How to:
```shell
git checkout [master|branch|commit]
git tag buildMe
git push [origin|upstream] buildMe
git tag --delete buildMe   #delete local tag
git push --delete [origin|upstream] buildMe   #delete remote tag
```
* tagname …

GitHub Actions Draft Releases to dev-unstable and dev-master

---

src/main/flight/pid.c

* raise dTermLPF1 to 90 to reduce over-filtered defaults.
* as the original lowering to 65 was debatable, so is raising it to 90.

raise default dTermLPF1 to 90

---

src/main/cms/cms_menu_imu.c
src/main/interface/settings.c
src/main/sensors/gyro.h

* use `uint8_t` for `smith_predict_filt_hz` rather than `uint16_t`
* fix range for both CLI and OSD (1-250)
* needs testing/validation before merge

Smith predict uint8 rather than 16

---

src/main/blackbox/blackbox.c
src/main/cms/cms_menu_imu.c
src/main/flight/pid.c
src/main/flight/pid.h
src/main/interface/settings.c
src/main/target/ALIENWHOOP/config.c
src/main/target/BEEBRAIN_BL/config.c
src/main/target/NBDBBBLV2/config.c
src/main/target/NBDHMBF4PRO/config.c

* ~return~ add dLPF2 type.
* needs testing. (OSD, flight, BBL, etc)
* ~needs validation same variable names as historical.~ never existed in BuF/Emu.

add dLPF2 type

---

src/main/common/sdft.c
src/main/flight/pid.c
src/main/sensors/gyroanalyse.c

* fix Codacy `The scope of the variable 'XXXXX' can be reduced.`
* set `dtermDynNotch = false` by default

fix PR#500; dynamicFilter/dynamicDtermNotch

---

src/main/interface/settings.c

* rename `dynamic_gyro_notch_width` to `dynamic_gyro_notch_q`
* fix `dterm_dyn_notch_q` range  `1-1000`, not `0-2000`

DynamicFilters name and range fixes

---

src/main/flight/pid.c

Project MockingBird has noted that the current angle mod implementation is not very responsive. This code change removes scaling on pitch and roll, which should in theory allow angle mode to go past your set max angle when pitch and roll are full. However it seems that event rarely or never occurs and allowing this results in a better flying experience.

Making angle mode more responsive

---

src/main/drivers/accgyro/accgyro.h

With beginning of GCC 9 a great deal of warnings of "unaligned pointer value"
are introduced. For dropping the warning:
```
taking address of packed member of 'struct accDev_s' may result in an
unaligned pointer value [-Waddress-of-packed-member]
```
simply remove the 'packing' similar to commit:
[5b09b397a74e76fff4be254b35576b1aea321368](https://github.com/emuflight/EmuFlight/commit/5b09b397a74e76fff4be254b35576b1aea321368)
The __attribute__((packed)) means the smallest possible alignment (1 byte),
usually used for implementing binary network protocols.

Remove packed on accDev_t for dropping alignment warning

---

src/main/pg/pg.c
src/main/pg/pg.h

The function cast in macro PG_REGISTER_ARRAY_WITH_RESET_FN wants
(pgResetFunc)(void * /* base */)
rather than
(pgResetFunc)(void * /* base */, int /* size */);
This commit fixes the warning caused by incompatible function types.
Note: This fix is already available also in https://github.com/betaflight/betaflight/blob/daf202e8c365d14aeeb8a0942b7a0356a11d30d8/src/main/pg/pg.h#L44
and
https://github.com/betaflight/betaflight/blob/daf202e8c365d14aeeb8a0942b7a0356a11d30d8/src/main/pg/pg.c#L56

Fix warning cast between incompatible function types

---

src/main/rx/rx.c

This commit fixes warning:
statement may fall through [-Wimplicit-fallthrough=]
This patch is also borrowed from betaflight to fix the above described problem:
https://github.com/betaflight/betaflight/blob/daf202e8c365d14aeeb8a0942b7a0356a11d30d8/src/main/rx/rx.c#L589

Fix warning statement may fall through

---

src/main/msc/emfat.c

Fix out of bounds buffer problems caused by employing incorrect sizes
VOL_LABEL_LEN != 12 in bs->volume_label
FILE_NAME_SHRT_LEN + FILE_NAME_EXTN_LEN != 8 in entry->name

Fix buffer is accessed out of bounds

---

src/main/fc/fc_rc.c
src/main/interface/settings.c
src/main/interface/settings.h
src/main/sensors/gyro.c
src/main/sensors/gyro.h

* port [BF's yaw_spin_recovery AUTO](https://github.com/betaflight/betaflight/pull/9455) 
* `Allow a 25% or minimum 200dps overshoot tolerance` of rc yaw rate 
* default `yaw_spin_recovery = AUTO`
* needs further testing
* flew 1 quad and test-hovered 2 others as well
Co-authored-by: nerdCopter <56646290+nerdCopter@users.noreply.github.com>

yaw_spin_recovery AUTO

---

src/main/pg/rx.c

* default RC smoothing interpolation 21 RPTY
* because pilots dont tune it, and most submitted logs have stepping feeding into PIDS.

revert rc-smoothing to interpolation (manual 21 RPTY)

---

src/main/drivers/vtx_common.h

Reverts emuflight/EmuFlight#829
* although convenient, may interrupt pitmode-on-switch or power-on-switch

Revert "default vtx_low_power_disarm = ON"

---

src/main/target/AIRBOTF7HDV/target.h
src/main/target/CLRACINGF7/target.h
src/main/target/MATEKF722HD/target.h
src/main/target/MATEKF722PX/target.h
src/main/target/RUSH_BLADE_F7_HD/target.h

* multiple targets fix `#define USE_LED_STRIP` (was wrongly `USE_LEDSTRIP`)

multiple targets fix USE_LED_STRIP

---

src/main/target/MATEKF722PX/target.c
src/main/target/MATEKF722PX/target.h
src/main/target/MATEKF722PX/target.mk

Tested fix for Black Box on MATEKF722PX target
As well as some minor upkeep to fix a definition for SPI2 pin and remove MAX7456 osd definitions as this FC uses FrskyOSD, which is not currently supported by Emuflight. 
Merge if approved. 
Closes #858

Target Updates - MATEKF722PX - Fixed Black Box

---

src/main/interface/msp.c
src/main/sensors/gyro.c

Gyro average was being performed twice for helio and strixf10 flight controllers. This update fixes this and simplifies the math for other targets as well.
HEX files: 
[HELIOSPRING_FixedStableMode_Analog.zip](https://github.com/emuflight/EmuFlight/files/11444111/HELIOSPRING_FixedStableMode_Analog.zip)

Fixes helio attitude estimation

---

src/main/target/FLYWOOF411_5IN1_AIO/target.h

* fix `FLYWOOF411_5IN1_AIO` icm42688p gyro/acc align
[EmuFlight_0.4.2_FLYWOOF411_5IN1_AIO_Build_712d1cb7e_ICM42688P_analog_needs_test.hex.zip](https://github.com/emuflight/EmuFlight/files/11668373/EmuFlight_0.4.2_FLYWOOF411_5IN1_AIO_Build_712d1cb7e_ICM42688P_analog_needs_test.hex.zip)

[Target] fix FLYWOOF411_5IN1_AIO ICM42688P align

---

src/main/target/MATEKF722SE/target.h
src/main/target/MATEKF722SE/target.mk

* fixes mpu6500 gyro not available for pilot (@kaji331) 
* https://github.com/emuflight/EmuFlight/issues/926#issuecomment-1672639664

MATEKF722SE - allow mpu6500 on gyro 1 and/or mpu6000 on gyro 2

---

src/main/cms/cms_menu_imu.c

* add Gyro LPF2-type to OSD
* tested - OSD/Configurator synchronization good.
* moved gLPF1-type to top

add Gyro LPF2 type to OSD

---

src/main/blackbox/blackbox.c
src/main/cms/cms_menu_imu.c
src/main/interface/msp.c
src/main/interface/settings.c
src/main/sensors/gyro.c
src/main/sensors/gyro.h
src/main/sensors/gyro_filter_impl.h
src/main/target/NBDBBBLV2/config.c
src/main/target/NBDBBBLV3/config.c
src/main/target/NBDHMBF41S/config.c
src/main/target/NBDHMBF4PRO/config.c
src/test/unit/sensor_gyro_unittest.cc

- fix/add USE_GYRO_LPF2 gating
- tested OSD and Configurator; Configurator resets to zero's when refresh as expected.

fix/add USE_GYRO_LPF2 gating

---

src/main/flight/pid.c
src/main/flight/pid.h
src/main/interface/msp.c
src/main/interface/settings.c
src/main/interface/settings.h
src/main/sensors/gyro.c
src/main/sensors/gyro.h

* revert some USE_GYRO_DATA_ANALYSE and USE_GYRO_LPF2 gating because C compiler sucks
* why: because compiler reports `warning: embedding a directive within macro arguments is not portable`, which reports that `ifdef` inside macros may have unexpected results depending on compiler/devices.
* reverting these requires reverting variables. and thus revert MSP read of values. (but not MSP write of `0`'s)

revert some USE_GYRO_DATA_ANALYSE and USE_GYRO_LPF2 gating

---

src/main/drivers/accgyro/accgyro_spi_icm426xx.c
src/main/drivers/bus_spi.c

* ICM426XX - Disable AFSR
* Betaflight: Disable ICM426XX AFSR feature to prevent stalls
* Ardupilot: AP_InertialSensor: fix for ICM42688 stuck gyro issue
these undocumented bits in register 0x4d control the "adaptive full
scale range" mode of the ICM42688. The feature is enabled by default
but has a bug where it gives "stuck" gyro values for short periods
(between 1ms and 2ms):, leading to a significant gyro bias at longer
time scales, enough to in some cases cause a vehicle to crash if it is
unable to switch to an alternative IMU
* Thanks to all participants here: https://github.com/betaflight/betaflight/issues/12970
* Thanks to @DutchFPV for quick-turnaround testing
* Thanks to Betaflight devs communications
Co-authored-by: Andrew Tridgell <andrew@tridgell.net>
Co-authored-by: Steve …

ICM426XX - Disable AFSR

---

src/main/target/SPBE_SPEEDYBEEF7V3/target.c
src/main/target/SPBE_SPEEDYBEEF7V3/target.h
src/main/target/SPBE_SPEEDYBEEF7V3/target.mk

* Resolves https://github.com/emuflight/EmuFlight/issues/875
* needs testing before merge: [EmuFlight_0.4.2_SPBE_SPEEDYBEEF7V3_Build_03ccb6745_Analog.hex.zip](https://github.com/emuflight/EmuFlight/files/13300718/EmuFlight_0.4.2_SPBE_SPEEDYBEEF7V3_Build_03ccb6745_Analog.hex.zip)
tested by @coffee-lord
- [Yes] hex Flash & subsequent USB connect
- [Yes] Gyro
- [Yes] Accelerometer
- [Yes] Motors
- [Yes] Onboard ADC
- [Untested] OSD (analog)
- [Untested] Smart Audio controls
- [Untested] Beeper/Alarm switch
- [Yes] Barometer
- [Yes] Blackbox sdcard/flash-chip
- [Untested] LED Strip
- [Untested] GPS
- [Yes] BlueTooth (if applicable)

[target] add SPEEDYBEEF7V3 with BMI270

---

src/main/target/FOXEERF722V4/target.c
src/main/target/FOXEERF722V4/target.h
src/main/target/FOXEERF722V4/target.mk

* rebuilt this target via script
* works un-soldered
* icm42688p works
* 16mb flash works
* 6 uarts + vcp
* **_needs flight testing_**
PLEASE TEST and FEEDBACK: 
[EmuFlight_0.4.2_FOXEERF722V4_ICM42688P.zip](https://github.com/emuflight/EmuFlight/files/13300825/EmuFlight_0.4.2_FOXEERF722V4_ICM42688P.zip)
HDzero version requires [dev-build Configurator](https://github.com/emuflight/dev-unstable/releases/tag/cfg-598).
- [Yes/No/Untested] hex Flash & subsequent USB connect
- [Yes/No/Untested] Gyro 
- [Yes/No/Untested] Accelerometer
- [Yes/No/Untested] Motors
- [Yes/No/Untested] Onboard ADC
- [Yes/No/Untested] OSD (analog)
- [Yes/No/Untested] Smart Audio controls
- [Yes/No/Untested] Beeper/Alarm switch
- [Yes/No/Untested] Barometer
- [Yes/No/Untested] Blackbox  flash-chip/sdcard
- …

[Target] FOXEERF722V4 ICM42668P MPU6000

---

.github/workflows/build.yml

use datestamp as tag for dev-unstable dev-master
not build number which loses sorting

[gh actions] use date as tag for dev-unstable dev-master

---

src/main/telemetry/ghst.c

fixes: 
```C
./src/main/telemetry/ghst.c:85:17: warning: 'getGhstFrame' defined but not used [-Wunused-function]
85 | STATIC_UNIT_TESTED uint8_t *getGhstFrame(){
```

fix compiler warning - comment out getGhstFrame (defined but not used)

---

lib/main/STM32F4/Drivers/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_spi.c
lib/main/STM32F7/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_uart.c

suppresses (does not attempt to fix 3rd party libraries):
```C
./lib/main/STM32F4/Drivers/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_spi.c: In function 'I2S_Init':
./lib/main/STM32F4/Drivers/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_spi.c:426:7: warning: this condition has identical branches [-Wduplicated-branches]
426 |     if((RCC->PLLCFGR & RCC_PLLCFGR_PLLSRC) == RCC_PLLCFGR_PLLSRC_HSE)
|       ^
./lib/main/STM32F7/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_uart.c: In function 'HAL_UART_Init':
./lib/main/STM32F7/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_uart.c:251:5: warning: this condition has identical branches [-Wduplicated-branches]
251 |   if(huart->Init.HwFlowCtl != UART_HWCONTROL_NONE)
|     ^
```
ref: https://stackoverflow.com/a/76435158/2013805

suppress (don't fix) compiler warnings for 3rd party libraries - STM32F4 and STM32F7

---

src/main/cms/cms.c
src/main/cms/cms_menu_blackbox.c
src/main/io/osd.c
src/main/io/osd.h
src/main/pg/vcd.h

- Text centering for OSD init (logo/etc), OSD CMS Menu's, and OSD Disarm-Statistics.
- unsure if this is complete, but works for Init, OSD CMS menu and disarm Statistics.
- tested one Analog and two HDZero.
- i noticed "Rebooting" and "Erasing Flash" text does not display on HDZero. :frowning_face:   (same as `master`)
- may be room for improvement, but much better than master.
Test DVR of this PR and PR 991 merged together. (some improvement committed after these DVR, but still valid for showing)
- HDZero Race v3 - https://youtu.be/qXyr4467I3g
- HDZero Freestyle v2 - https://youtu.be/656tzch6jZ8
- Analog - https://youtu.be/ShBYZvr1A8o
Everything was too left before:
after

HDZERO - OSD Init/Menu/Stats Centering

---

src/main/target/FOXEERF745V3_AIO/target.c
src/main/target/FOXEERF745V3_AIO/target.h
src/main/target/FOXEERF745V3_AIO/target.mk

* resolves https://github.com/emuflight/EmuFlight/issues/877
* need testing [EmuFlight_0.4.2_FOXE_FOXEERF745V3_AIO_Build_605d948ee_Analog_needs_testing.hex.zip](https://github.com/emuflight/EmuFlight/files/13310998/EmuFlight_0.4.2_FOXE_FOXEERF745V3_AIO_Build_605d948ee_Analog_needs_testing.hex.zip)
- [Yes/No/Untested] _**Is the Serial Count correct? (ports tab)**_
- [Yes/No/Untested] hex Flash & subsequent USB connect
- [Yes/No/Untested] Gyro 
- [Yes/No/Untested] Accelerometer
- [Yes/No/Untested] Motors
- [Yes/No/Untested] Onboard ADC
- [Yes/No/Untested] OSD (analog)
- [Yes/No/Untested] Smart Audio controls
- [Yes/No/Untested] Beeper/Alarm switch
- [Yes/No/Untested] Barometer
- [Yes/No/Untested] Blackbox  flash-chip/sdcard
- [Yes/No/Untested] LED Strip
- [Yes/No/Untested] GPS
- …

[target] add FOXEERF745V3_AIO with ICM42688P

---

src/main/target/SPEEDYBEE_F745_AIO/target.c
src/main/target/SPEEDYBEE_F745_AIO/target.h
src/main/target/SPEEDYBEE_F745_AIO/target.mk

* resolves #921
* needs testing EmuFlight_0.4.2_SPBE_SPEEDYBEE_F745_AIO_Build_ab2c2a3c8_Analog_needs_testing_incl_serial_count.hex.zip](https://github.com/emuflight/EmuFlight/files/13310816/EmuFlight_0.4.2_SPBE_SPEEDYBEE_F745_AIO_Build_ab2c2a3c8_Analog_needs_testing_incl_serial_count.hex.zip)
- [Yes/No/Untested] _**Is the Serial Count correct? (ports tab)**_
- [Yes/No/Untested] hex Flash & subsequent USB connect
- [Yes/No/Untested] Gyro 
- [Yes/No/Untested] Accelerometer
- [Yes/No/Untested] Motors
- [Yes/No/Untested] Onboard ADC
- [Yes/No/Untested] OSD (analog)
- [Yes/No/Untested] Smart Audio controls
- [Yes/No/Untested] Beeper/Alarm switch
- [Yes/No/Untested] Barometer
- [Yes/No/Untested] Blackbox  flash-chip/sdcard
- [Yes/No/Untested] LED Strip
- [Yes/No/Untested] GPS
- …

[target] add SPEEDYBEE_F745_AIO with MPU6000

---

src/main/target/TUNERCF405/target.c
src/main/target/TUNERCF405/target.h
src/main/target/TUNERCF405/target.mk

* needs testing [EmuFlight_0.4.2_TURC_TUNERCF405_Build_572b73774_Analog_needs_testing.hex.zip](https://github.com/emuflight/EmuFlight/files/13312364/EmuFlight_0.4.2_TURC_TUNERCF405_Build_572b73774_Analog_needs_testing.hex.zip)
- [Yes/No/Untested] hex Flash & subsequent USB connect
- [Yes/No/Untested] Gyro 
- [Yes/No/Untested] Accelerometer
- [Yes/No/Untested] Is the Serial Count correct? (Ports tab UARTs)
- [Yes/No/Untested] Motors
- [Yes/No/Untested] Onboard ADC
- [Yes/No/Untested] OSD (analog)
- [Yes/No/Untested] Smart Audio controls
- [Yes/No/Untested] Beeper/Alarm switch
- [Yes/No/Untested] Barometer
- [Yes/No/Untested] Blackbox  flash-chip/sdcard
- [Yes/No/Untested] LED Strip
- [Yes/No/Untested] GPS
- [Yes/No/Untested] BlueTooth (if applicable)

[target] add TUNERCF405 with BMI270

---

src/main/target/BEEBRAIN_PRO/target.h
src/main/target/BEEBRAIN_PRO/target.mk

- resolves https://github.com/emuflight/EmuFlight/issues/735

[targets] BEEBRAIN_PRO_DSM_US/INTL add BMI160

---

src/main/flight/mixer.c

- this seems to have fixed it. motor output signals are correct.
- **_needs 3D flight testing and feedback_**
- [please test https://github.com/emuflight/dev-unstable/releases/tag/20240618.193242-hex](https://github.com/emuflight/dev-unstable/releases/tag/20240709.141832-hex)
- Tested good without props on BLHeli32 32.9.5 and BlueJay 0.16.
- Tested good with props on Bluejay 0.16. I did not "fly", but it rotates each axis properly and was able to hover inverted.
- BlueJay 0.17, 0.18, 0.19 are known to have broken 3D startup power.  Seemingly fixed in BlueJay 0.21-RC1, but BlueJay developers would like BlackBox logs for further analysis.
Please test-fly and report feedback this PR or Discord.
<hr>
- tentative 3D-mode fix 
- broken in https://github.com/emuflight/EmuFlight/pull/398
- fixes …

3D-mode fix

---

src/main/vcpf4/usbd_desc.c

- before: 
- after:
- when defined in target.h:

more descriptive USBD_PRODUCT_STRING when not defined in target.h

---

src/main/target/IFLIGHT_BLITZ_F411RX/target.c
src/main/target/IFLIGHT_BLITZ_F411RX/target.h
src/main/target/IFLIGHT_BLITZ_F411RX/target.mk

- CC2500 version
- needs testing: [EmuFlight_0.4.3_IFLIGHT_BLITZ_F411RX_Build_2db3cdfc1.hex.zip](https://github.com/emuflight/EmuFlight/files/15486192/EmuFlight_0.4.3_IFLIGHT_BLITZ_F411RX_Build_2db3cdfc1.hex.zip)
- requires newer Configurator: https://github.com/emuflight/dev-master/releases/tag/20240501.162228-cfg
closes #867

[target] add IFLIGHT_BLITZ_F411RX - CC2500 version

---

src/main/fc/fc_core.c
src/main/fc/rc_controls.c
src/main/fc/rc_controls.h
src/main/interface/settings.c

- Arming still requires PreArm switch.
- `set prearm_allow_rearm = ON`, default is `OFF`.
- This allows re-arming mid-air, still **_requiring_** preArm, but without need for PreArm AUX _resetting_.
- TESTED SUCCESSFUL
- Required for mid-air rearm: `set small_angle = 180` (when using ACC)
- **WARNING** - it is very hard to coordinate 0 throttle (**_required_** for arming) in mid-air.
originally on Betaflight PR https://github.com/betaflight/betaflight/pull/14013

PreArm allow Re-Arm (without resetting PreArm AUX)
